# Generated by Django 3.0.6 on 2020-05-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='head',
            field=models.TextField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
